name: pymice-analyzer
channels:
  - defaults
dependencies:
  - python=3.6
  - anaconda
  - pyhamcrest # twisted requires this but conda doesn't install it for some reason
  - wxpython
  - pip:
    - black
    - gooey
    - pymice
    - pypubsub # wxpython requires this but conda doesn't install it for some reason
